[package]
name = "remdb-macros"
version = "0.1.4"
edition = "2024"
authors = ["remdb contributors"]
description = "Macros for remdb embedded memory database"
license = "MIT"
documentation = "https://docs.rs/remdb-macros"
homepage = "https://github.com/bobjia/remdb"
repository = "https://github.com/bobjia/remdb"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
